// AUTO-GENERATED by content_scaffold — do not edit.
declare module 'virtual:content' {
  export const managed_websites: { "services": Array<{ "title": string; "description": string; "id": string }>; "ownershipPoints": Array<string>; "customerPoints": Array<string> };
}
